### ISSUE TITLE
Is there a method to search by tags via scrapping?

### ISSUE THREAD

**Issue by gabrielglbh** [h7x4ABk3g/unofficial_jisho_api_dart#2]
I see that `uriForPhraseScrape` point to the `https://jisho.org/word/...`, and all other scrap methods point to other urls.

If I want to search all N5 words from Jisho I want to point to `https://jisho.org/search/...` with `searchTerm` as `#jlpt-n5`.

Is there a way to achieve this using this API? or is something that needs to be worked on?

(Love your work h7x4)

**Comment by h7x4** [comment]
Hey! Thanks for asking!

The four API calls implemented are scraping a single kanji, scraping a single word, scraping for example sentences, and searching the native API. As of now, there is no scraping functionality for `/search`. The way I've been using it, is by showing multiple words to the user from the native API (`searchForPhrase`), which does support options like `#jlpt-n5`, wildcards, etc. If the user wants to see further details on a specific word, I scrape `/word` with `scrapeForPhrase`. This adds a little bit more details, but most of the data is just duplicated. Prefetching the details for all native API results might also be possible, but it will probably put quite a strain on jisho.

Right now, the API is almost identical to [the one mistval has made for javascript](https://github.com/mistval/unofficial-jisho-api). I have been planning to do a complete rehaul of the API in the future (maybe next autumn). This will probably make it go astray from the javascript library, unless mistval agrees to some large pull requests. The rewrite might introduce a better way to use the special search options, but for now I think the native API is the best solution.

(Btw, I really enjoy your KanPractise app!)
